version: "3.9"
services:
  banco:
    image: postgres
    container_name: banco_de_dados
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: encurtador
      POSTGRES_USER: ian
    ports:
      - "5432:5432"
  back:
    image: ianvictor/hackaton_ads:v1.0
    env_file:
      - back.env
    ports:
      - "8080:8080"
    depends_on:
      - banco
  front:
    image: ianvictor/hackaton_ads_front:v8.0
    env_file:
      - front.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - back
networks:
  default:
    driver: bridge